# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

# Υλοποιήσεις μέσω Heap: ADTPriorityQueue
# Το Heap χρησιμοποιεί Vector, οπότε χρειαζόμαστε και μια υλοποίηση του ADTVector.
#
#UsingLinkedTree_ADTRecTree_test_OBJS  = ADTRecTree_test.o $(MODULES)/UsingLinkedTree/ADTRecTree.o 
#UsingMap_ADTRecTree_test_OBJS  = ADTRecTree_test.o $(MODULES)/UsingADTMap/ADTRecTree.o $(MODULES)/ADTMap.o $(MODULES)/ADTSet.o
ADTRecTree_utils_test_OBJS  = ADTRecTree_utils_test.o $(MODULES)/UsingLinkedTree/ADTRecTree.o $(MODULES)/ADTRecTree_utils.o $(MODULES)/ADTSet.o


#$(MODULES)/UsingDynamicArray/ADTVector.o

# Ο βασικός κορμός του Makefile
include ../common.mk